config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "sessions#new"

  resources :users, only: [:create, :show, :edit, :update]
  resources :songs, only: [:create, :index, :new, :edit, :update, :destroy]
  resources :artists

  get "songs/search", to: "songs#search", as: :search

  post "songs/:queryterm", to: "songs#query", as: :query

  get "/signup", to: "users#new", as: :signup

  get "/profile", to: "users#profile", as: :profile

  get "/login", to: "sessions#new", as: :login
  post "/login", to: "sessions#create", as: :new_session
  delete "/logout", to: "sessions#destroy", as: :logout
end

app/views/shared/_error.html.erb
<% if errors && errors.size > 0 %>
  <ul class="input-errors">
    <% errors.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar">
    <!-- NAVIGATION LINKS -->
    <h1 id='title'>Song Of the Day App (SODA!)</h1>
    <!-- PROFILE LINK -->
    <div id='profile' class="p-2">
        <%= link_to("|Profile|", "/users/#{@current_user[:id]}") %>
    </div>
    <div id='profile' class="p-2">
        <%= link_to("|Edit Profile|", "/users/#{@current_user[:id]}/edit") %>
    </div>
        <!-- Favorite Song link -->
    <div id='profile' class="p-2">
        <%= link_to("|Favorite Songs|", "/songs")%>
        <%= link_to("|Favorite Artists|", "/artists")%>

    </div>



    <!-- SONG SEARCH -->
    <div id='search' class="p-2">
        <%= link_to("|Add Song|", search_path) %>
    </div>
    <!-- LOGOUT -->
    <div id='logout' class="p-2">
        <%= link_to("|Logout|", logout_path, method: "delete") %>
    </div>
</div>